@echo off
REM ****************************************************************************
REM Vivado (TM) v2022.1 (64-bit)
REM
REM Filename    : compile.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for compiling the simulation design source files
REM
REM Generated by Vivado on Sun Jul 24 23:58:17 -0400 2022
REM SW Build 3526262 on Mon Apr 18 15:48:16 MDT 2022
REM
REM IP Build 3524634 on Mon Apr 18 20:55:01 MDT 2022
REM
REM usage: compile.bat
REM
REM ****************************************************************************

set xv_cxl_lib_path=""
set xv_cpt_lib_path=""
set xv_ext_lib_path=""
set xv_boost_lib_path="D:/Xilinx/Vivado/2022.1/tps/boost_1_72_0"

REM compile C design sources
echo "xsc -c --gcc_compile_options "-I%xv_boost_lib_path%" -work xil_defaultlib -f testbench_c.prj"
call xsc  -c --gcc_compile_options "-I%xv_boost_lib_path%" -work xil_defaultlib -f testbench_c.prj 2> xsc_err.log
call type xsc.log >> compile.log
call type xsc_err.log >> compile.log
call type xsc_err.log
REM compile Verilog/System Verilog design sources
echo "xvlog --incr --relax -L uvm -prj testbench_vlog.prj"
call xvlog  --incr --relax -L uvm -prj testbench_vlog.prj -log xvlog.log
call type xvlog.log > compile.log
if "%errorlevel%"=="1" goto END
if "%errorlevel%"=="0" goto SUCCESS
:END
exit 1
:SUCCESS
exit 0
